GET http://localhost:1234/users

### Create user
POST http://localhost:1234/users
Content-Type: application/json

{                                             
    "nombre": "Camilo",
    "dob": "2000-01-01",
    "adress": "Ejemplo St.",
    "description": "Alguna descripción",
    "createdAt": "2023-01-01"
}

### Update user

PATCH http://localhost:1234/users/Ejemplo
Content-Type: application/json

{
    "description": "hola"
}

### Delete user

DELETE http://localhost:1234/users/María